/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import database.koneksi;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class frameDataPelanggan extends javax.swing.JFrame {
    
    koneksi objekku;
    DefaultTableModel modelTabelDataPelanggan;

    /**
     * Creates new form frameDataPelanggan
     */
    public frameDataPelanggan() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekku = new koneksi();
        modelTabelDataPelanggan = new DefaultTableModel();
        jTableDataPelanggan.setModel(modelTabelDataPelanggan);
        modelTabelDataPelanggan.addColumn("ID Pelanggan");
        modelTabelDataPelanggan.addColumn("ID User");
        modelTabelDataPelanggan.addColumn("Nama Pelanggan");
        modelTabelDataPelanggan.addColumn("Jenis Kelamin");
        modelTabelDataPelanggan.addColumn("No Telpon");
        modelTabelDataPelanggan.addColumn("Tanggal Lahir");
        modelTabelDataPelanggan.addColumn("Token");
        modelTabelDataPelanggan.addColumn("Alamat");
        loadTabelDataPelanggan();
    }
    
    void loadTabelDataPelanggan(){
        try {
            String sql = "SELECT * FROM tbl_datapelanggan";
            PreparedStatement kueri = objekku.konekDB.prepareStatement(sql);
            ResultSet data = kueri.executeQuery();
            
            while (data.next()) {
                Object[] baris = new Object[8];
                baris[0] = data.getString("id_pelanggan");
                baris[1] = data.getString("id_user");
                baris[2] = data.getString("nama_pelanggan");
                baris[3] = data.getString("jenis_kelamin");
                baris[4] = data.getString("no_telpon");
                baris[5] = data.getString("tgl_lahir");
                baris[6] = data.getString("token");
                baris[7] = data.getString("alamat");
                
                modelTabelDataPelanggan.addRow(baris);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDPelanggan = new javax.swing.JTextField();
        txtIDUser = new javax.swing.JTextField();
        txtNamaPelanggan = new javax.swing.JTextField();
        txtNoTelpon = new javax.swing.JTextField();
        txtTanggalLahir = new javax.swing.JTextField();
        txtToken = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataPelanggan = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtJenisKelamin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Pelanggan");

        jLabel2.setText("ID Pelanggan");

        jLabel3.setText("ID User");

        jLabel4.setText("Nama Pelanggan");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("No Telpon");

        jLabel7.setText("Tanggal Lahir");

        jLabel8.setText("Token");

        jLabel9.setText("Alamat");

        txtIDUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDUserActionPerformed(evt);
            }
        });

        txtNoTelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelponActionPerformed(evt);
            }
        });

        jTableDataPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDataPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDataPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDataPelanggan);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtToken))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUbah)
                                .addGap(32, 32, 32)
                                .addComponent(btnHapus))
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAlamat, txtIDPelanggan, txtIDUser, txtJenisKelamin, txtNamaPelanggan, txtNoTelpon, txtTanggalLahir, txtToken});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSimpan)
                        .addComponent(btnUbah))
                    .addComponent(btnHapus))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUserActionPerformed

    private void txtNoTelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelponActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
            String sqlUbah = "UPDATE tbl_datapelanggan SET id_user=?, nama_pelanggan=?, jenis_kelamin=?, no_telpon=?, tgl_lahir=?, token=?, alamat=? WHERE id_pelanggan=?";
            
            PreparedStatement kueri = objekku.konekDB.prepareStatement(sqlUbah);
            
            kueri.setString(8, txtIDPelanggan.getText());
            kueri.setString(1, txtIDUser.getText());
            kueri.setString(2, txtNamaPelanggan.getText());
            kueri.setString(3, txtJenisKelamin.getText());
            kueri.setString(4, txtNoTelpon.getText());
            kueri.setString(5, txtTanggalLahir.getText());
            kueri.setString(6, txtToken.getText());
            kueri.setString(7, txtAlamat.getText());
            
            kueri.executeUpdate();
            loadTabelDataPelanggan();
                
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            String sqlHapus = "DELETE FROM tbl_datapelanggan WHERE id_pelanggan = ?";
            PreparedStatement kueri = objekku.konekDB.prepareStatement(sqlHapus);
        
            kueri.setString(1, txtIDUser.getText());
            
            kueri.executeUpdate();
            loadTabelDataPelanggan();
            
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIDPelanggan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Id Pelanggan Belum Diisi");
                txtIDPelanggan.requestFocus();
            } else if
               (txtIDUser.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Id User Belum Diisi");
                txtIDUser.requestFocus();
            } else if
               (txtNamaPelanggan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Pelanggan Belum Diisi");
                txtNamaPelanggan.requestFocus();
            } else if
               (txtJenisKelamin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Jenis Kelamin Belum Diisi");
                txtJenisKelamin.requestFocus();
            } else if
               (txtNoTelpon.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Telpon Belum Diisi");
                txtNoTelpon.requestFocus();
            } else if
               (txtTanggalLahir.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tanggal Lahir Belum Diisi");
                txtTanggalLahir.requestFocus();
            } else if
               (txtToken.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Token Belum Diisi");
                txtToken.requestFocus();
            } else if
               (txtAlamat.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Alamat Belum Diisi");
                txtAlamat.requestFocus();
            } else {
                String sqlCari = "SELECT * FROM tbl_datapelanggan WHERE id_pelanggan = ?";
                PreparedStatement cari = objekku.konekDB.prepareStatement(sqlCari);
                cari.setString(1, txtIDPelanggan.getText());
                ResultSet hasil = cari.executeQuery();
                
                if (hasil.next()) {
                JOptionPane.showMessageDialog(this, "ID Pelanggan Sudah Ada");
                txtIDPelanggan.setText(hasil.getString("id_pelanggan"));
                txtIDUser.setText(hasil.getString("id_user"));
                txtNamaPelanggan.setText(hasil.getString("nama_pelanggan"));
                txtJenisKelamin.setText(hasil.getString("jenis_kelamin"));
                txtNoTelpon.setText(hasil.getString("no_telpon"));
                txtTanggalLahir.setText(hasil.getString("tgl_lahir"));
                txtToken.setText(hasil.getString("token"));
                txtAlamat.setText(hasil.getString("alamat"));
                } else {
                
                String sqlSimpan = "INSERT INTO tbl_datapelanggan VALUES (?,?,?,?,?,?,?,?)";
                PreparedStatement kueri = objekku.konekDB.prepareStatement(sqlSimpan);
                
                kueri.setString(1, txtIDPelanggan.getText());
                kueri.setString(2, txtIDUser.getText());
                kueri.setString(3, txtNamaPelanggan.getText());
                kueri.setString(4, txtJenisKelamin.getText());
                kueri.setString(5, txtNoTelpon.getText());
                kueri.setString(6, txtTanggalLahir.getText());
                kueri.setString(7, txtToken.getText());
                kueri.setString(8, txtAlamat.getText());
                
                kueri.executeUpdate();
                loadTabelDataPelanggan();
                
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTableDataPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDataPelangganMouseClicked
        // TODO add your handling code here:
        int i = jTableDataPelanggan.getSelectedRow();
        
        String id_pelanggan = jTableDataPelanggan.getValueAt(i, 0).toString();
        String id_user = jTableDataPelanggan.getValueAt(i, 1).toString();
        String nama_pelanggan = jTableDataPelanggan.getValueAt(i, 2).toString();
        String jenis_kelamin = jTableDataPelanggan.getValueAt(i, 3).toString();
        String no_telpon = jTableDataPelanggan.getValueAt(i, 4).toString();
        String tgl_lahir = jTableDataPelanggan.getValueAt(i, 5).toString();
        String token = jTableDataPelanggan.getValueAt(i, 6).toString();
        String alamat = jTableDataPelanggan.getValueAt(i, 7).toString();
        
        txtIDPelanggan.setText(id_pelanggan);
        txtIDUser.setText(id_user);
        txtNamaPelanggan.setText(nama_pelanggan);
        txtJenisKelamin.setText(jenis_kelamin);
        txtNoTelpon.setText(no_telpon);
        txtTanggalLahir.setText(tgl_lahir);
        txtToken.setText(token);
        txtAlamat.setText(alamat);
    }//GEN-LAST:event_jTableDataPelangganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDataPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDataPelanggan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtIDPelanggan;
    private javax.swing.JTextField txtIDUser;
    private javax.swing.JTextField txtJenisKelamin;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNoTelpon;
    private javax.swing.JTextField txtTanggalLahir;
    private javax.swing.JTextField txtToken;
    // End of variables declaration//GEN-END:variables
}
